
[env]
TERM = "xterm-256color"

[terminal.shell]
program = "/usr/bin/zsh"
args = ["-l"]

[window]
decorations = "Full" # "Full" | "None"
startup_mode = "Maximized" # "Windowed" | "Maximized" | "Fullscreen"
dynamic_padding = true
opacity = 0.80

[font]
normal = { family = "ComicShannsMono Nerd Font", style = "Bold" }
size = 14

[cursor]
style = { shape = "Underline", blinking = "On" }
thickness = 0.30
blink_interval = 200
blink_timeout = 0

[mouse]
hide_when_typing = true
bindings = [
  { mouse = "Right", mods = "Control", action = "Paste" },
]

[general]
import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/themes/catppuccin-latte.toml"
  # "~/.config/alacritty/themes/catppuccin-frappe.toml"
  #"~/.config/alacritty/themes/catppuccin-macchiato.toml"
  "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[terminal]
